//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shaitanet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> MasterID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Review Review { get; set; }
    }
}
